<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TagihanRondasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tagihan_rondas')->delete();
        
        \DB::table('tagihan_rondas')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ronda_id' => 1,
                'warga_id' => 45,
                'tgl_absen_ronda' => '2025-04-01 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:53',
                'updated_at' => '2025-04-11 14:34:53',
            ),
            1 => 
            array (
                'id' => 2,
                'ronda_id' => 1,
                'warga_id' => 42,
                'tgl_absen_ronda' => '2025-04-01 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:53',
                'updated_at' => '2025-04-11 14:34:53',
            ),
            2 => 
            array (
                'id' => 3,
                'ronda_id' => 1,
                'warga_id' => 11,
                'tgl_absen_ronda' => '2025-04-01 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:53',
                'updated_at' => '2025-04-11 14:34:53',
            ),
            3 => 
            array (
                'id' => 4,
                'ronda_id' => 1,
                'warga_id' => 46,
                'tgl_absen_ronda' => '2025-04-01 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            4 => 
            array (
                'id' => 5,
                'ronda_id' => 1,
                'warga_id' => 23,
                'tgl_absen_ronda' => '2025-04-01 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            5 => 
            array (
                'id' => 6,
                'ronda_id' => 2,
                'warga_id' => 27,
                'tgl_absen_ronda' => '2025-04-02 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            6 => 
            array (
                'id' => 7,
                'ronda_id' => 2,
                'warga_id' => 37,
                'tgl_absen_ronda' => '2025-04-02 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            7 => 
            array (
                'id' => 8,
                'ronda_id' => 2,
                'warga_id' => 59,
                'tgl_absen_ronda' => '2025-04-02 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            8 => 
            array (
                'id' => 9,
                'ronda_id' => 2,
                'warga_id' => 24,
                'tgl_absen_ronda' => '2025-04-02 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 1,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-17 11:33:57',
            ),
            9 => 
            array (
                'id' => 10,
                'ronda_id' => 2,
                'warga_id' => 51,
                'tgl_absen_ronda' => '2025-04-02 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            10 => 
            array (
                'id' => 11,
                'ronda_id' => 3,
                'warga_id' => 53,
                'tgl_absen_ronda' => '2025-04-03 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            11 => 
            array (
                'id' => 12,
                'ronda_id' => 3,
                'warga_id' => 10,
                'tgl_absen_ronda' => '2025-04-03 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            12 => 
            array (
                'id' => 13,
                'ronda_id' => 3,
                'warga_id' => 31,
                'tgl_absen_ronda' => '2025-04-03 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            13 => 
            array (
                'id' => 14,
                'ronda_id' => 3,
                'warga_id' => 56,
                'tgl_absen_ronda' => '2025-04-03 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            14 => 
            array (
                'id' => 15,
                'ronda_id' => 3,
                'warga_id' => 39,
                'tgl_absen_ronda' => '2025-04-03 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            15 => 
            array (
                'id' => 16,
                'ronda_id' => 4,
                'warga_id' => 14,
                'tgl_absen_ronda' => '2025-04-04 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            16 => 
            array (
                'id' => 17,
                'ronda_id' => 4,
                'warga_id' => 17,
                'tgl_absen_ronda' => '2025-04-04 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            17 => 
            array (
                'id' => 18,
                'ronda_id' => 4,
                'warga_id' => 29,
                'tgl_absen_ronda' => '2025-04-04 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            18 => 
            array (
                'id' => 19,
                'ronda_id' => 4,
                'warga_id' => 4,
                'tgl_absen_ronda' => '2025-04-04 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            19 => 
            array (
                'id' => 20,
                'ronda_id' => 4,
                'warga_id' => 1,
                'tgl_absen_ronda' => '2025-04-04 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            20 => 
            array (
                'id' => 21,
                'ronda_id' => 5,
                'warga_id' => 52,
                'tgl_absen_ronda' => '2025-04-05 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            21 => 
            array (
                'id' => 22,
                'ronda_id' => 5,
                'warga_id' => 6,
                'tgl_absen_ronda' => '2025-04-05 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            22 => 
            array (
                'id' => 23,
                'ronda_id' => 5,
                'warga_id' => 20,
                'tgl_absen_ronda' => '2025-04-05 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            23 => 
            array (
                'id' => 24,
                'ronda_id' => 5,
                'warga_id' => 16,
                'tgl_absen_ronda' => '2025-04-05 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            24 => 
            array (
                'id' => 25,
                'ronda_id' => 5,
                'warga_id' => 22,
                'tgl_absen_ronda' => '2025-04-05 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            25 => 
            array (
                'id' => 26,
                'ronda_id' => 6,
                'warga_id' => 48,
                'tgl_absen_ronda' => '2025-04-06 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            26 => 
            array (
                'id' => 27,
                'ronda_id' => 6,
                'warga_id' => 21,
                'tgl_absen_ronda' => '2025-04-06 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            27 => 
            array (
                'id' => 28,
                'ronda_id' => 6,
                'warga_id' => 41,
                'tgl_absen_ronda' => '2025-04-06 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            28 => 
            array (
                'id' => 29,
                'ronda_id' => 6,
                'warga_id' => 60,
                'tgl_absen_ronda' => '2025-04-06 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            29 => 
            array (
                'id' => 30,
                'ronda_id' => 6,
                'warga_id' => 35,
                'tgl_absen_ronda' => '2025-04-06 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            30 => 
            array (
                'id' => 31,
                'ronda_id' => 7,
                'warga_id' => 40,
                'tgl_absen_ronda' => '2025-04-07 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            31 => 
            array (
                'id' => 32,
                'ronda_id' => 7,
                'warga_id' => 62,
                'tgl_absen_ronda' => '2025-04-07 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            32 => 
            array (
                'id' => 33,
                'ronda_id' => 7,
                'warga_id' => 18,
                'tgl_absen_ronda' => '2025-04-07 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            33 => 
            array (
                'id' => 34,
                'ronda_id' => 7,
                'warga_id' => 5,
                'tgl_absen_ronda' => '2025-04-07 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            34 => 
            array (
                'id' => 35,
                'ronda_id' => 7,
                'warga_id' => 44,
                'tgl_absen_ronda' => '2025-04-07 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            35 => 
            array (
                'id' => 36,
                'ronda_id' => 8,
                'warga_id' => 36,
                'tgl_absen_ronda' => '2025-04-08 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            36 => 
            array (
                'id' => 37,
                'ronda_id' => 8,
                'warga_id' => 43,
                'tgl_absen_ronda' => '2025-04-08 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            37 => 
            array (
                'id' => 38,
                'ronda_id' => 8,
                'warga_id' => 63,
                'tgl_absen_ronda' => '2025-04-08 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            38 => 
            array (
                'id' => 39,
                'ronda_id' => 8,
                'warga_id' => 28,
                'tgl_absen_ronda' => '2025-04-08 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            39 => 
            array (
                'id' => 40,
                'ronda_id' => 8,
                'warga_id' => 61,
                'tgl_absen_ronda' => '2025-04-08 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            40 => 
            array (
                'id' => 41,
                'ronda_id' => 9,
                'warga_id' => 49,
                'tgl_absen_ronda' => '2025-04-09 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            41 => 
            array (
                'id' => 42,
                'ronda_id' => 9,
                'warga_id' => 7,
                'tgl_absen_ronda' => '2025-04-09 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            42 => 
            array (
                'id' => 43,
                'ronda_id' => 9,
                'warga_id' => 15,
                'tgl_absen_ronda' => '2025-04-09 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 1,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:40:53',
            ),
            43 => 
            array (
                'id' => 44,
                'ronda_id' => 9,
                'warga_id' => 3,
                'tgl_absen_ronda' => '2025-04-09 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            44 => 
            array (
                'id' => 45,
                'ronda_id' => 9,
                'warga_id' => 25,
                'tgl_absen_ronda' => '2025-04-09 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            45 => 
            array (
                'id' => 46,
                'ronda_id' => 10,
                'warga_id' => 55,
                'tgl_absen_ronda' => '2025-04-10 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            46 => 
            array (
                'id' => 47,
                'ronda_id' => 10,
                'warga_id' => 32,
                'tgl_absen_ronda' => '2025-04-10 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            47 => 
            array (
                'id' => 48,
                'ronda_id' => 10,
                'warga_id' => 19,
                'tgl_absen_ronda' => '2025-04-10 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            48 => 
            array (
                'id' => 49,
                'ronda_id' => 10,
                'warga_id' => 13,
                'tgl_absen_ronda' => '2025-04-10 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            49 => 
            array (
                'id' => 50,
                'ronda_id' => 10,
                'warga_id' => 30,
                'tgl_absen_ronda' => '2025-04-10 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:34:54',
                'updated_at' => '2025-04-11 14:34:54',
            ),
            50 => 
            array (
                'id' => 51,
                'ronda_id' => 11,
                'warga_id' => 50,
                'tgl_absen_ronda' => '2025-04-11 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            51 => 
            array (
                'id' => 52,
                'ronda_id' => 11,
                'warga_id' => 58,
                'tgl_absen_ronda' => '2025-04-11 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            52 => 
            array (
                'id' => 53,
                'ronda_id' => 11,
                'warga_id' => 38,
                'tgl_absen_ronda' => '2025-04-11 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            53 => 
            array (
                'id' => 54,
                'ronda_id' => 11,
                'warga_id' => 54,
                'tgl_absen_ronda' => '2025-04-11 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            54 => 
            array (
                'id' => 55,
                'ronda_id' => 11,
                'warga_id' => 64,
                'tgl_absen_ronda' => '2025-04-11 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            55 => 
            array (
                'id' => 56,
                'ronda_id' => 12,
                'warga_id' => 57,
                'tgl_absen_ronda' => '2025-04-12 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            56 => 
            array (
                'id' => 57,
                'ronda_id' => 12,
                'warga_id' => 2,
                'tgl_absen_ronda' => '2025-04-12 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            57 => 
            array (
                'id' => 58,
                'ronda_id' => 12,
                'warga_id' => 8,
                'tgl_absen_ronda' => '2025-04-12 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 1,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-05-17 20:09:52',
            ),
            58 => 
            array (
                'id' => 59,
                'ronda_id' => 12,
                'warga_id' => 47,
                'tgl_absen_ronda' => '2025-04-12 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            59 => 
            array (
                'id' => 60,
                'ronda_id' => 12,
                'warga_id' => 12,
                'tgl_absen_ronda' => '2025-04-12 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            60 => 
            array (
                'id' => 61,
                'ronda_id' => 13,
                'warga_id' => 26,
                'tgl_absen_ronda' => '2025-04-13 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            61 => 
            array (
                'id' => 62,
                'ronda_id' => 13,
                'warga_id' => 9,
                'tgl_absen_ronda' => '2025-04-13 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            62 => 
            array (
                'id' => 63,
                'ronda_id' => 13,
                'warga_id' => 33,
                'tgl_absen_ronda' => '2025-04-13 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
            63 => 
            array (
                'id' => 64,
                'ronda_id' => 13,
                'warga_id' => 34,
                'tgl_absen_ronda' => '2025-04-13 00:00:00',
                'nominal_tagihan' => 10000,
                'status_denda' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-17 11:27:01',
                'updated_at' => '2025-04-17 11:27:01',
            ),
        ));
        
        
    }
}