<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Master\Models\Warga;

class WargasTableSeeder extends Seeder
{

  /**
   * Auto generated seed file
   *
   * @return void
   */
  public function run()
  {


    \DB::table('wargas')->delete();

    \DB::table('wargas')->insert(array(
      0 =>
        array(
          'id' => 1,
          'nama' => 'Rifqi Munawar Ridwan',
          'telp' => '085151145097',
          'alamat' => 'D7 No. 11',
          'nik' => '3203210512010003',
          'jk' => 'Laki-laki',
          'kota_kelahiran' => 'Cianjur',
          'tgl_lahir' => '2001-11-05',
          'agama' => '1',
          'pendidikan' => '5',
          'pekerjaan' => '12',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'admin',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-01-17 11:30:04',
          'updated_at' => '2025-02-09 01:20:09',
        ),
      1 =>
        array(
          'id' => 2,
          'nama' => 'HENDRA SUPRIADI',
          'telp' => '085151145097',
          'alamat' => 'Blok A',
          'nik' => '3203210512010003',
          'jk' => 'Perempuan',
          'kota_kelahiran' => 'Bandung',
          'tgl_lahir' => '2007-02-06',
          'agama' => '1',
          'pendidikan' => '5',
          'pekerjaan' => '12',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'admin',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-01-18 20:02:11',
          'updated_at' => '2025-01-18 22:25:27',
        ),
      2 =>
        array(
          'id' => 3,
          'nama' => 'Udin Petot',
          'telp' => '085151145097',
          'alamat' => 'bandung',
          'nik' => '1278010404040004',
          'jk' => 'Perempuan',
          'kota_kelahiran' => 'Bandung',
          'tgl_lahir' => '2007-02-06',
          'agama' => '1',
          'pendidikan' => '5',
          'pekerjaan' => '12',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'unknown',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-01-21 00:34:20',
          'updated_at' => '2025-01-21 00:34:20',
        ),
      3 =>
        array(
          'id' => 4,
          'nama' => 'Ronaldo',
          'telp' => '085151145097',
          'alamat' => 'portugal',
          'nik' => '1278010404040004',
          'jk' => 'Perempuan',
          'kota_kelahiran' => 'Bandung',
          'tgl_lahir' => '2007-02-06',
          'agama' => '1',
          'pendidikan' => '5',
          'pekerjaan' => '12',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'unknown',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-01-21 00:38:58',
          'updated_at' => '2025-01-21 00:38:58',
        ),
      4 =>
        array(
          'id' => 5,
          'nama' => 'Leonel Messi',
          'telp' => '085151145097',
          'alamat' => 'argentina',
          'nik' => '1278010404040004',
          'jk' => 'Perempuan',
          'kota_kelahiran' => 'Bandung',
          'tgl_lahir' => '2007-02-06',
          'agama' => '1',
          'pendidikan' => '5',
          'pekerjaan' => '12',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'unknown',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-01-21 00:39:18',
          'updated_at' => '2025-01-21 00:39:18',
        ),
      5 =>
        array(
          'id' => 6,
          'nama' => 'Antony El-Gasing',
          'telp' => '085151145097',
          'alamat' => 'Al hilal',
          'nik' => '3203210000000',
          'jk' => 'Perempuan',
          'kota_kelahiran' => 'Bandung',
          'tgl_lahir' => '2007-02-06',
          'agama' => '1',
          'pendidikan' => '5',
          'pekerjaan' => '12',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'unknown',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-02-09 00:59:35',
          'updated_at' => '2025-02-09 00:59:35',
        ),
      6 =>
        array(
          'id' => 7,
          'nama' => 'SAMANI BIN TUKIMIN',
          'telp' => '085151145097',
          'alamat' => 'BLOK PON',
          'nik' => '085624011773',
          'jk' => 'Laki-laki',
          'kota_kelahiran' => 'Cirebon',
          'tgl_lahir' => '2025-02-02',
          'agama' => '1',
          'pendidikan' => '5',
          'pekerjaan' => '7',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'admin',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-02-09 21:09:55',
          'updated_at' => '2025-03-02 17:44:36',
        ),
      7 =>
        array(
          'id' => 8,
          'nama' => 'Dilan',
          'telp' => '085151145097',
          'alamat' => 'Cirebon',
          'nik' => '1278010404040004',
          'jk' => 'Laki-laki',
          'kota_kelahiran' => 'Bandung',
          'tgl_lahir' => '2007-02-06',
          'agama' => '1',
          'pendidikan' => '3',
          'pekerjaan' => '12',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'admin',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-02-24 21:39:39',
          'updated_at' => '2025-03-08 17:18:18',
        ),
      8 =>
        array(
          'id' => 9,
          'nama' => 'Budi Santoso',
          'telp' => '081345678912',
          'alamat' => 'Bandung',
          'nik' => '3275010303030003',
          'jk' => 'Laki-laki',
          'kota_kelahiran' => 'Bandung',
          'tgl_lahir' => '1987-12-10',
          'agama' => '2',
          'pendidikan' => '4',
          'pekerjaan' => '10',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'admin',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-02-24 21:39:39',
          'updated_at' => '2025-03-08 17:18:33',
        ),
      9 =>
        array(
          'id' => 10,
          'nama' => 'Dewi Lestari',
          'telp' => '089876543210',
          'alamat' => 'Medan',
          'nik' => '1278010404040004',
          'jk' => 'Perempuan',
          'kota_kelahiran' => 'Medan',
          'tgl_lahir' => '1998-04-05',
          'agama' => '1',
          'pendidikan' => '5',
          'pekerjaan' => '15',
          'status_perkawinan' => '1',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'admin',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-02-24 21:39:39',
          'updated_at' => '2025-03-08 17:19:11',
        ),
      10 =>
        array(
          'id' => 11,
          'nama' => 'Eko Prasetyo',
          'telp' => '081290876543',
          'alamat' => 'Yogyakarta',
          'nik' => '3471010505050005',
          'jk' => 'Laki-laki',
          'kota_kelahiran' => 'Yogyakarta',
          'tgl_lahir' => '1992-09-30',
          'agama' => '3',
          'pendidikan' => '2',
          'pekerjaan' => '10',
          'status_perkawinan' => '3',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'admin',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-02-24 21:39:39',
          'updated_at' => '2025-03-08 17:19:32',
        ),
      11 =>
        array(
          'id' => 12,
          'nama' => 'Indah Permata',
          'telp' => '082134567890',
          'alamat' => 'Semarang',
          'nik' => '3374010606060006',
          'jk' => 'Perempuan',
          'kota_kelahiran' => 'Semarang',
          'tgl_lahir' => '2000-03-18',
          'agama' => '1',
          'pendidikan' => '4',
          'pekerjaan' => '2',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'admin',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-02-24 21:39:39',
          'updated_at' => '2025-02-24 21:45:39',
        ),
      12 =>
        array(
          'id' => 13,
          'nama' => 'Rudi Hartono',
          'telp' => '085678909876',
          'alamat' => 'Palembang',
          'nik' => '1671010707070007',
          'jk' => 'Laki-laki',
          'kota_kelahiran' => 'Palembang',
          'tgl_lahir' => '1985-06-12',
          'agama' => '2',
          'pendidikan' => '4',
          'pekerjaan' => '2',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'admin',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-02-24 21:39:39',
          'updated_at' => '2025-02-24 21:45:39',
        ),
      13 =>
        array(
          'id' => 14,
          'nama' => 'Sari Wulandari',
          'telp' => '089012345678',
          'alamat' => 'Makassar',
          'nik' => '7371010808080008',
          'jk' => 'Perempuan',
          'kota_kelahiran' => 'Makassar',
          'tgl_lahir' => '1997-01-23',
          'agama' => '2',
          'pendidikan' => '4',
          'pekerjaan' => '2',
          'status_perkawinan' => '2',
          'status_keluarga' => '1',
          'created_by' => 'admin',
          'updated_by' => 'admin',
          'deleted_by' => NULL,
          'deleted_at' => NULL,
          'created_at' => '2025-02-24 21:39:39',
          'updated_at' => '2025-02-24 21:45:39',
        ),
    ));

    Warga::factory()->count(50)->create();

  }
}
